spring:
    profiles:
        active:
            - testH2
    application:
        name: sgmc-back
    security:   
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8089/realms/sgmc         
            client:
                registration:
                    sgmc:
                        provider: keycloak
                        client-id: sgmc
                        client-secret: 2wuAGkrVdfoDWfJxMuAtYqRmxXT0k73W
                        authorization-grant-type: client_credentials
                provider:
                    keycloak:
                        token-uri: http://localhost:8089/realms/sgmc/protocol/openid-connect/token